# conda version 24.7.1
# mamba version 1.5.9
# miniforge

## somehow this does not work with stardist.....
name: morphody39
channels:
#  - defaults
  - conda-forge
  - nodefaults #this is a channel that enforces avoidance of the defaults channel
#  - pytorch
#  - nvidia
dependencies:
  - python
  - pip

  - aicsimageio
  - anndata
  - bioconda::snakemake
  
  - colour
#  - conda-lock #could be useful in future
#  - conda-pack #could be useful in future
  - czifile #reordered this from above colour
  - hdbscan
  - imbalanced-learn
  - ipywidgets
  - jpype1
  - jupyterlab
  - jupytext
  # possibly add jupyterlab_kernel_usage (with an add-on) or jupyter-resource-usage
  - lxml
  - matplotlib
  - microfilm #this includes matplotlib-scalebar, and could be useful for quick plotting of multichannel things
  - napari=0.4.18 #this has to be this version otherwise on newer versions you get segfaults on labels
  # when you try and combine with packages that use numba
  # I think it was napari 0.4.19post1 that was the problem
  - napari-aicsimageio
  - natsort
  - notebook
  - numba
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pillow
  - pims
  - pystackreg

  - pyqt
  - pytables
  - readlif
  - requests
  - scanpy
  - scikit-image
  - scikit-learn
#  - singularity
  - tqdm
  - umap-learn
  - xlrd
  - xlwt
  - xmlschema
  - xmltodict

#lxml
# - urllib3=2.0.7 #this is the version that morphodynamics tries to install, replacing another one if not specified
  - pip:
#    - tensorflow[and-cuda]
#    - morphodynamics
#    - git+https://github.com/guiwitz/napari-morphodynamics.git
#    - cellpose[gui] #We recommend python 3.8, but python 3.9 and 3.10 will likely work as well
    - aicspylibczi
#    - btrack
#    - czitools #this package changes a lot of tools from the conda environment, so 
#       if I need it I will have to solve for this later or put it in a different environment
    - ipynb
    - lxml_html_clean
