# conda version 24.7.1
# mamba version 1.5.9
# miniforge

name: btrack4
channels:
#  - defaults
  - conda-forge
  - nodefaults #this is a channel that enforces avoidance of the defaults channel
dependencies:
  - python
  - pip
  
  - btrack
  - pydantic=1.10.14
  - ipython
  - pip:


